# Generated by Django 4.1.7 on 2023-03-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idee',
            options={'verbose_name_plural': 'Idee'},
        ),
        migrations.AlterModelOptions(
            name='votant',
            options={'verbose_name_plural': 'Votant'},
        ),
    ]
