# Generated by Django 4.1.7 on 2023-03-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppale', '0002_alter_idee_options_alter_votant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='idee',
            name='score',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
