# Generated by Django 4.1.7 on 2026-04-08 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppale', '0003_idee_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='idee',
            name='vues_recentes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
