# Generated by Django 4.1.7 on 2024-05-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppale', '0004_userselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='poisson',
            field=models.CharField(blank=True, choices=[('agneau', 'Agneau'), ('boeuf', 'Boeuf'), ('canard', 'Canard'), ('dinde', 'Dinde'), ('lapin', 'Lapin'), ('porc', 'Porc'), ('poulet', 'Poulet'), ('veau', 'Veau')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='feculent',
            field=models.CharField(blank=True, choices=[('boulgour', 'Boulgour'), ('maïs', 'Maïs'), ('pain', 'Pain'), ('pâtes', 'Pâtes'), ('pomme_de_terre', 'Pomme de terre'), ('quinoa', 'Quinoa'), ('riz', 'Riz'), ('semoule', 'Semoule')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='legume',
            field=models.CharField(blank=True, choices=[('asperge', 'Asperge'), ('aubergine', 'Aubergine'), ('betterave', 'Betterave'), ('brocoli', 'Brocoli'), ('carotte', 'Carotte'), ('céleri', 'Céleri'), ('chou-fleur', 'Chou-fleur'), ('chou de Bruxelles', 'Chou de Bruxelles'), ('chou rouge', 'Chou rouge'), ('concombre', 'Concombre'), ('courgette', 'Courgette'), ('épinard', 'Épinard'), ('fenouil', 'Fenouil'), ('haricot vert', 'Haricot vert'), ('laitue', 'Laitue'), ('navet', 'Navet'), ('oignon', 'Oignon'), ('poireau', 'Poireau'), ('poivron', 'Poivron'), ('pomme de terre', 'Pomme de terre'), ('radis', 'Radis'), ('tomate', 'Tomate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='viande',
            field=models.CharField(blank=True, choices=[('agneau', 'Agneau'), ('boeuf', 'Boeuf'), ('canard', 'Canard'), ('dinde', 'Dinde'), ('lapin', 'Lapin'), ('porc', 'Porc'), ('poulet', 'Poulet'), ('veau', 'Veau')], max_length=100),
        ),
    ]
