# Generated by Django 4.1.7 on 2026-04-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppale', '0004_idee_vues_recentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='idee',
            name='affection',
            field=models.CharField(choices=[(' 5/5', 'Trop Passione'), ('3/5', 'Moyen Passione'), ('1.5/5', 'Faible Passione'), ('NA', 'Na')], default='NC', max_length=25),
        ),
    ]
