# Generated by Django 4.1.7 on 2026-04-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppale', '0005_idee_affection'),
    ]

    operations = [
        migrations.CreateModel(
            name='bets_faits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bet', models.CharField(max_length=200, null=True)),
                ('type_pari', models.CharField(max_length=200, null=True)),
                ('côte', models.IntegerField(blank=True, default=100)),
                ('confiance', models.CharField(max_length=200, null=True)),
                ('résultat', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
