# Generated by Django 4.1.7 on 2024-09-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppale", "0005_userselection_poisson_alter_userselection_feculent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userselection",
            name="temps_préparation_souhaité",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
