# Generated by Django 4.1.7 on 2024-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppale", "0006_userselection_temps_préparation_souhaité"),
    ]

    operations = [
        migrations.AddField(
            model_name="userselection",
            name="choix_user",
            field=models.CharField(
                blank=True,
                choices=[
                    ("temps_preparation_1", "Temps de préparation 1"),
                    ("temps_preparation_2", "Temps de préparation 2"),
                    ("temps_preparation_3", "Temps de préparation 3"),
                ],
                max_length=20,
            ),
        ),
    ]
