# Generated by Django 4.1.7 on 2024-09-25 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ppale", "0008_userselection_temps_preparation_souhaite_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userselection",
            name="temps_preparation_souhaite_1",
        ),
        migrations.RemoveField(
            model_name="userselection",
            name="temps_preparation_souhaite_2",
        ),
        migrations.RemoveField(
            model_name="userselection",
            name="temps_preparation_souhaite_3",
        ),
    ]
