# Generated by Django 4.1.7 on 2024-09-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authenti", "0003_user_temps_preparation_1_user_temps_preparation_2_and_more"),
        ("ppale", "0011_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idee",
            name="auteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authenti.user"
            ),
        ),
        migrations.AlterField(
            model_name="prepa",
            name="votant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authenti.user"
            ),
        ),
        migrations.AlterField(
            model_name="votant",
            name="votant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authenti.user"
            ),
        ),
    ]
