# Generated by Django 4.1.7 on 2023-03-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
