name: Django Continuous Integration workflow

on:
    push:
        branches:
            - 'dev6'
        paths:
            - 'tests/**'
            - '.github/workflows/django_ci.yml'
            - 'requirements.txt'
            - 'manage.py'
            - 'abstract_ideas/**'
            - 'authenti/**'
            - 'autre_test_azure.py'
            - 'db.sqlite3'
            - 'django/**'
            - 'ppale/**'
            - 'static/**'
            - 'templates/**'
            - 'venv/**'
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - dev6
        paths:
            - 'tests/**'
            - '.github/workflows/django_ci.yml'
            - 'requirements.txt'
            - 'manage.py'
            - 'abstract_ideas/**'
            - 'authenti/**'
            - 'autre_test_azure.py'
            - 'db.sqlite3'
            - 'django/**'
            - 'ppale/**'
            - 'static/**'
            - 'templates/**'
            - 'venv/**'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run Django migrations
              run: python manage.py migrate

            - name: Run specific test
              run: python manage.py test ppale.tests
              continue-on-error: true  # Continue even if tests fail

            - name: Install Bandit
              run: pip install bandit

            - name: Run Security Check
              run: bandit -r .
              continue-on-error: true

            - name: Check Syntax
              run: pycodestyle --statistics --ignore=E501,E712 .
              continue-on-error: true
